from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("6.4.1")

##### setup singularity #####
# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"

##### load rules #####
#include: "rules/extract_info_summary.smk"
#include: "rules/create_fasta_filter_intact.smk"
#include: "rules/extract_info_detail.smk"
#include: "rules/recognizer.smk"
include: "rules/abricate.smk"
#include: "rules/taxonomy_classification.smk"
#include: "rules/defense_systems.smk"
#include: "rules/homology_extract.smk"

##### target rules #####
rule all:
    input:
        #f"{sys.path[0]}/../../results/result_dict.csv", #extract_info_summary
        #f"{sys.path[0]}/../../results/prophages_frequency.png", #extract_info_summary
        #f"{sys.path[0]}/../../results/distribution_plots.png", #extract_info_summary
        #f"{sys.path[0]}/../../results/prophages.json", #extract_info_summary
        #f"{sys.path[0]}/../../results/radar_chart.png",          #extract_info_summary
        #f"{sys.path[0]}/../../results/fasta_cds_recognizer.fasta",  #extract_info_detail
        #directory(f"{sys.path[0]}/../../results/output_recognizer"),  #recognizer
        #f"{sys.path[0]}/../../results/df_att.csv",    #create_fasta_filter_intact
        #f"{sys.path[0]}/../../results/fasta_filter.fasta",   #create_fasta_filter_intact
        expand("results/{database}.tab", database=["vfdb", "card", "resfinder"]),
        f"{sys.path[0]}/../../results/abricate_summary.tab",         #abricate
        f"{sys.path[0]}/../../results/heatmap_virulence.png",        #abricate
        #f"{sys.path[0]}/../../results/taxonomy_class/out/phagcn_prediction.csv",    #taxonomic_classification
        #f"{sys.path[0]}/../../results/taxonomy_plot.png",      #taxonomic_classification
        #directory(f"{sys.path[0]}/../../results/padloc_results"),   #defense_systems
        #f"{sys.path[0]}/../../results/defense_systems.png",    #defense_systems
        #f"{sys.path[0]}/../../results/homology_extraction.csv"
